### ISSUE TITLE
The visible captcha is not resolved

### ISSUE THREAD

**Issue by aodjhyk16ocdi6** [Euro-pol/turnaround-api#7]
Hello, I'm trying to solve a visible captcha. In your example(modrinth.com) hidden captcha is solved without problems, but when using visible captcha on the test site 2captcha captcha is not solved

Using your host turn.seized.live and my host the problem remains.

```
body = {
    "sitekey": "0x4AAAAAAAVrOwQWPlm3Bnr5",
    "url": "https://2captcha.com/demo/cloudflare-turnstile",
    "invisible": False
}
```

**Comment by aodjhyk16ocdi6** [comment]
archive repo, bro

**Comment by Euro-pol** [comment]
no
